export type Player = {
  id: string;
  name: string;
  rating: number;
  position: string;
  club: string;
  league?: string;
  nation: string;
  price: number;
  pace: number;
  shooting: number;
  passing: number;
  dribbling: number;
  defending: number;
  physical: number;
  image: string;
  age?: number;
  preferredFoot?: "Left" | "Right";
  height?: string;
  weight?: string;
  playstyles?: Array<{ name: string; description: string; plus?: boolean }>;
  attributes?: Record<string, number>;
  edition?: string;
};